// GENERATED CODE — DO NOT EDIT BY HAND.
// Regenerate with `npm run generate` from internal/api/docs/swagger.json
// in the goose repo.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/api/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delete a chain
         * @description Returns all configured proxy chains (ordered lists of pool layers).
         *     Returns the chain with the given id.
         *     Creates (or replaces) a proxy chain: an ordered list of layers, each referencing a pool (which carries its own filters + selector). Layer 0 is the first hop; each subsequent layer is dialed through the previous.
         *     Removes the chain with the given id. Inbounds whose policy still references it will fail to resolve until reconfigured.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.ChainSpec"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.ChainSpec"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.ChainSpec"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Delete a chain
         * @description Returns all configured proxy chains (ordered lists of pool layers).
         *     Returns the chain with the given id.
         *     Creates (or replaces) a proxy chain: an ordered list of layers, each referencing a pool (which carries its own filters + selector). Layer 0 is the first hop; each subsequent layer is dialed through the previous.
         *     Removes the chain with the given id. Inbounds whose policy still references it will fail to resolve until reconfigured.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.ChainSpec"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.ChainSpec"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.ChainSpec"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delete a chain
         * @description Returns all configured proxy chains (ordered lists of pool layers).
         *     Returns the chain with the given id.
         *     Creates (or replaces) a proxy chain: an ordered list of layers, each referencing a pool (which carries its own filters + selector). Layer 0 is the first hop; each subsequent layer is dialed through the previous.
         *     Removes the chain with the given id. Inbounds whose policy still references it will fail to resolve until reconfigured.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Chain id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.ChainSpec"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.ChainSpec"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.ChainSpec"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a chain
         * @description Returns all configured proxy chains (ordered lists of pool layers).
         *     Returns the chain with the given id.
         *     Creates (or replaces) a proxy chain: an ordered list of layers, each referencing a pool (which carries its own filters + selector). Layer 0 is the first hop; each subsequent layer is dialed through the previous.
         *     Removes the chain with the given id. Inbounds whose policy still references it will fail to resolve until reconfigured.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Chain id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.ChainSpec"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.ChainSpec"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.ChainSpec"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get engine configuration
         * @description Returns the engine-level configuration: network stack selection, admin API settings, metrics DB path and offline geo database settings.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Engine"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delete an inbound
         * @description Returns all configured inbound listeners.
         *     Returns the inbound listener with the given id.
         *     Creates (or replaces) an inbound listener. When the body carries no id, the id must be supplied in the URL path (/api/inbounds/{id}); when both are present they must match. Changes apply live: the engine starts/stops listeners on the next config version bump.
         *     Removes the inbound listener with the given id and stops it.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.Inbound"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Inbound"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Inbound"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Delete an inbound
         * @description Returns all configured inbound listeners.
         *     Returns the inbound listener with the given id.
         *     Creates (or replaces) an inbound listener. When the body carries no id, the id must be supplied in the URL path (/api/inbounds/{id}); when both are present they must match. Changes apply live: the engine starts/stops listeners on the next config version bump.
         *     Removes the inbound listener with the given id and stops it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.Inbound"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Inbound"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Inbound"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inbounds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delete an inbound
         * @description Returns all configured inbound listeners.
         *     Returns the inbound listener with the given id.
         *     Creates (or replaces) an inbound listener. When the body carries no id, the id must be supplied in the URL path (/api/inbounds/{id}); when both are present they must match. Changes apply live: the engine starts/stops listeners on the next config version bump.
         *     Removes the inbound listener with the given id and stops it.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Inbound id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.Inbound"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Inbound"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Inbound"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete an inbound
         * @description Returns all configured inbound listeners.
         *     Returns the inbound listener with the given id.
         *     Creates (or replaces) an inbound listener. When the body carries no id, the id must be supplied in the URL path (/api/inbounds/{id}); when both are present they must match. Changes apply live: the engine starts/stops listeners on the next config version bump.
         *     Removes the inbound listener with the given id and stops it.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Inbound id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.Inbound"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Inbound"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Inbound"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent request metrics
         * @description Returns up to n recent proxied-request records, newest first. n defaults to 100; values above 10000 are capped; invalid values fall back to the default.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Number of records to return (default 100, max 10000) */
                    n?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["core.RequestMetric"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outbounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delete an outbound
         * @description Returns all configured outbound proxy specs (static and provider-managed).
         *     Returns the outbound spec with the given id.
         *     Creates (or replaces) an outbound spec. The protocol names a registered outbound plugin (e.g. "direct", "http", "socks5", "psiphon"); config is the plugin-specific configuration map.
         *     Removes the outbound with the given id. Provider-managed outbounds are re-added by their provider on its next refresh.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.OutboundSpec"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.OutboundSpec"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.OutboundSpec"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Delete an outbound
         * @description Returns all configured outbound proxy specs (static and provider-managed).
         *     Returns the outbound spec with the given id.
         *     Creates (or replaces) an outbound spec. The protocol names a registered outbound plugin (e.g. "direct", "http", "socks5", "psiphon"); config is the plugin-specific configuration map.
         *     Removes the outbound with the given id. Provider-managed outbounds are re-added by their provider on its next refresh.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.OutboundSpec"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.OutboundSpec"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.OutboundSpec"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outbounds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delete an outbound
         * @description Returns all configured outbound proxy specs (static and provider-managed).
         *     Returns the outbound spec with the given id.
         *     Creates (or replaces) an outbound spec. The protocol names a registered outbound plugin (e.g. "direct", "http", "socks5", "psiphon"); config is the plugin-specific configuration map.
         *     Removes the outbound with the given id. Provider-managed outbounds are re-added by their provider on its next refresh.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Outbound id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.OutboundSpec"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.OutboundSpec"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.OutboundSpec"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete an outbound
         * @description Returns all configured outbound proxy specs (static and provider-managed).
         *     Returns the outbound spec with the given id.
         *     Creates (or replaces) an outbound spec. The protocol names a registered outbound plugin (e.g. "direct", "http", "socks5", "psiphon"); config is the plugin-specific configuration map.
         *     Removes the outbound with the given id. Provider-managed outbounds are re-added by their provider on its next refresh.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Outbound id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.OutboundSpec"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.OutboundSpec"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.OutboundSpec"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delete a pool
         * @description Returns all configured outbound pools (ordered outbound sets with filters + selection strategy).
         *     Returns the pool with the given id.
         *     Creates (or replaces) a pool: an ordered set of outbound ids plus the filters and selection strategy applied when picking from it.
         *     Removes the pool with the given id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.Pool"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Pool"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Pool"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Delete a pool
         * @description Returns all configured outbound pools (ordered outbound sets with filters + selection strategy).
         *     Returns the pool with the given id.
         *     Creates (or replaces) a pool: an ordered set of outbound ids plus the filters and selection strategy applied when picking from it.
         *     Removes the pool with the given id.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.Pool"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Pool"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Pool"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pools/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Delete a pool
         * @description Returns all configured outbound pools (ordered outbound sets with filters + selection strategy).
         *     Returns the pool with the given id.
         *     Creates (or replaces) a pool: an ordered set of outbound ids plus the filters and selection strategy applied when picking from it.
         *     Removes the pool with the given id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Pool id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.Pool"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Pool"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Pool"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a pool
         * @description Returns all configured outbound pools (ordered outbound sets with filters + selection strategy).
         *     Returns the pool with the given id.
         *     Creates (or replaces) a pool: an ordered set of outbound ids plus the filters and selection strategy applied when picking from it.
         *     Removes the pool with the given id.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Pool id */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: components["requestBodies"]["config.Pool"];
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Pool"];
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["config.Pool"];
                    };
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api.errResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        "api.errResponse": {
            /**
             * @description Error is a short, human-readable reason for the rejection.
             * @example missing id
             */
            error?: string;
        };
        "config.APIConfig": {
            listen?: string;
            /** @description Token is the bearer token for admin auth; empty disables auth. */
            token?: string;
        };
        "config.ChainSpec": {
            id?: string;
            /** @description PoolIDs, in order */
            layers?: string[];
        };
        "config.Engine": {
            /** @description API is the admin server config. */
            api?: components["schemas"]["config.APIConfig"];
            /** @description DB is the metrics database path. */
            db?: string;
            /** @description Geo is the offline IP database config. */
            geo?: components["schemas"]["config.GeoConfig"];
            /** @description Stack selects the network stack: "system" or "gvisor". */
            stack?: string;
        };
        "config.FilterSpec": {
            /** @description Params is filter-specific config, e.g. {"countries":["US"]}. */
            params?: {
                [key: string]: unknown;
            };
            /** @description Type is "location", "latency", "protocol". */
            type?: string;
        };
        "config.GeoConfig": {
            /** @description Path is the database file path. */
            path?: string;
            /** @description Type is "mmdb", "qqwry", "zxinc" or "" (disabled). */
            type?: string;
        };
        "config.Inbound": {
            id?: string;
            /** @description host:port */
            listen?: string;
            policy?: components["schemas"]["config.InboundPolicy"];
            /** @description "http" | "socks5" */
            protocol?: string;
            /** @description empty => no auth */
            users?: components["schemas"]["config.User"][];
        };
        "config.InboundPolicy": {
            /** @description ChainID references a Chain in the chain store. */
            chain_id?: string;
        };
        "config.OutboundSpec": {
            config?: {
                [key: string]: unknown;
            };
            id?: string;
            protocol?: string;
        };
        "config.Pool": {
            filters?: components["schemas"]["config.FilterSpec"][];
            id?: string;
            outbound_ids?: string[];
            selector?: components["schemas"]["config.SelectorSpec"];
        };
        "config.SelectorSpec": {
            /** @description Params is strategy-specific config, e.g. sticky: {"key":"domain"}. */
            params?: {
                [key: string]: unknown;
            };
            /** @description Type is "random", "roundrobin", "sticky", "leastlatency". */
            type?: string;
        };
        "config.User": {
            password?: string;
            /**
             * @description Policy overrides the inbound-level policy for this user. Empty fields
             *     fall back to the inbound-level policy.
             */
            policy?: components["schemas"]["config.InboundPolicy"];
            username?: string;
        };
        /** @enum {string} */
        "core.Network": "tcp" | "udp" | "tcp" | "udp";
        "core.RequestMetric": {
            chain?: string[];
            error?: string;
            finishedAt?: string;
            id?: string;
            inboundID?: string;
            latency?: components["schemas"]["time.Duration"];
            network?: components["schemas"]["core.Network"];
            startedAt?: string;
            success?: boolean;
            target?: string;
            user?: string;
        };
        /**
         * Format: int64
         * @enum {integer}
         */
        "time.Duration": 1 | 1000 | 1000000;
    };
    responses: never;
    parameters: never;
    requestBodies: {
        /** @description Chain to create */
        "config.ChainSpec": {
            content: {
                "application/json": components["schemas"]["config.ChainSpec"];
            };
        };
        /** @description Inbound to create */
        "config.Inbound": {
            content: {
                "application/json": components["schemas"]["config.Inbound"];
            };
        };
        /** @description Outbound to create */
        "config.OutboundSpec": {
            content: {
                "application/json": components["schemas"]["config.OutboundSpec"];
            };
        };
        /** @description Pool to create */
        "config.Pool": {
            content: {
                "application/json": components["schemas"]["config.Pool"];
            };
        };
    };
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
